title: ICDevs.org
email: admin@icdevs.org
description: >- # this means to ignore newlines until "baseurl:"
  A US 501(c)3 non-profit benefiting the Internet Computer and DFINITY ecosystem. Grants. Bounties. Education. Tutorials. Utilities. Open Source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter: ICDevs_org
github:  icdevs
mail: admin@icdevs.org
linkedin: xxx

# site settings
contact: true
about: true
who_we_are: true
donations: true
bounties: true
version: v0.1.0

# Theme settings

edit-date: false # show the date of last edit on pages
default-theme: sandcastle # pick which theme loads by default

# post settings

tags: foo bar
# development settings

developer-controls: false # show developer specefic tips

# Build settings
theme: jek
plugins:
  - jekyll-feed


markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class : 'syntax'

include:
  - .well-known
  - .ic-assets.json

